# Generated by Django 5.1.7 on 2025-04-22 12:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default=254700000000, help_text='Format: +254712345678 or 0712345678', max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid Kenyan phone number starting with +254, 254, 0, or 7 (e.g. +254712345678, 0712345678, 712345678)', regex='^(\\+?254|0)?[17]\\d{8}$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='designation',
            field=models.CharField(choices=[('admin', 'Administrator'), ('accountant', 'Accountant'), ('support', 'Support Staff'), ('technician', 'Network Technician'), ('manager', 'Manager')], default='support', help_text="Select the user's role in the system", max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(default='+254700000000', help_text='Format: +254712345678, 0712345678, or 712345678', max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid Kenyan phone number starting with +254, 254, 0, or 7 (e.g. +254712345678, 0712345678, 712345678)', regex='^(\\+?254|0)?[17]\\d{8}$')]),
        ),
    ]
