# Generated by Django 5.1.7 on 2025-04-22 16:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0002_remove_userprofile_address_remove_userprofile_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='hire_date',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(help_text='Format: +254712345678, 0712345678, or 712345678', max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid Kenyan phone number starting with +254, 254, 0, or 7 (e.g. +254712345678, 0712345678, 712345678)', regex='^(\\+?254|0)?[17]\\d{8}$')]),
        ),
        migrations.AddConstraint(
            model_name='userprofile',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_user_profile'),
        ),
    ]
