# Generated by Django 5.1.7 on 2025-04-23 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0004_alter_bandwidthpackage_options_alter_client_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsubscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
