# Generated by Django 5.1.7 on 2025-05-30 13:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0005_alter_clientsubscription_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Format: +254712345678 or 0712345678', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid Kenyan phone number starting with +254, 254, 0, or 7 (e.g. +254712345678, 0712345678, 712345678)', regex='^(\\+?254|0)?[17]\\d{8}$')]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Format: +254712345678, 0712345678, or 712345678', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid Kenyan phone number starting with +254, 254, 0, or 7 (e.g. +254712345678, 0712345678, 712345678)', regex='^(\\+?254|0)?[17]\\d{8}$')]),
        ),
    ]
