# Generated by Django 5.2.3 on 2025-07-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0006_alter_user_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Format: +254712345678 or 0712345678', max_length=15, null=True),
        ),
    ]
