# Generated by Django 5.2.3 on 2025-07-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0007_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='designation',
            field=models.CharField(blank=True, choices=[('admin', 'Administrator'), ('accountant', 'Accountant'), ('support', 'Support Staff'), ('technician', 'Network Technician'), ('manager', 'Manager')], default='support', help_text="Select the user's role in the system", max_length=50),
        ),
    ]
